using GymFit.Domain.Enums;
using GymFit.Infrastructure.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace GymFit.Web.Controllers;
[Authorize(Roles="Admin,Reception")]
public class ReportsController:Controller{
 private readonly ApplicationDbContext _db;public ReportsController(ApplicationDbContext db){_db=db;}
 public async Task<IActionResult> Index(DateTime? from,DateTime? to){var end=(to??DateTime.UtcNow.Date).Date.AddDays(1);var start=(from??end.AddDays(-30)).Date;if(start>=end)start=end.AddDays(-30);var revenue=await _db.Payments.Where(p=>p.PaymentDate>=start&&p.PaymentDate<end&&p.Status==PaymentStatus.Completed).SumAsync(p=>(decimal?)p.Amount)??0m;var payments=await _db.Payments.CountAsync(p=>p.PaymentDate>=start&&p.PaymentDate<end);var attendance=await _db.Attendances.CountAsync(a=>a.CheckInTime>=start&&a.CheckInTime<end);var newMembers=await _db.Members.CountAsync(m=>m.JoinDate>=start&&m.JoinDate<end);var activeMembers=await _db.Members.CountAsync(m=>m.IsActive);var activeSubs=await _db.Subscriptions.CountAsync(s=>s.IsActive&&s.Status==SubscriptionStatus.Active);var plans=await _db.MembershipPlans.AsNoTracking().Where(x=>x.IsActive).Select(x=>new{x.Name,Subscriptions=x.Subscriptions.Count(s=>s.IsActive)}).OrderByDescending(x=>x.Subscriptions).ToListAsync();var branch=await _db.Branches.AsNoTracking().Where(b=>b.IsActive).Select(b=>new{b.Name,Members=b.Members.Count(m=>m.IsActive),Revenue=b.Payments.Where(p=>p.PaymentDate>=start&&p.PaymentDate<end&&p.Status==PaymentStatus.Completed).Sum(p=>(decimal?)p.Amount)??0m}).OrderByDescending(x=>x.Revenue).ToListAsync();return View(new ReportViewModel{From=start,To=end.AddDays(-1),Revenue=revenue,Payments=payments,Attendance=attendance,NewMembers=newMembers,ActiveMembers=activeMembers,ActiveSubscriptions=activeSubs,PlanBreakdown=plans.Select(x=>new ReportPlanRow{Name=x.Name,Subscriptions=x.Subscriptions}).ToList(),BranchBreakdown=branch.Select(x=>new ReportBranchRow{Name=x.Name,Members=x.Members,Revenue=x.Revenue}).ToList()});}
}
public class ReportViewModel{public DateTime From{get;set;}public DateTime To{get;set;}public decimal Revenue{get;set;}public int Payments{get;set;}public int Attendance{get;set;}public int NewMembers{get;set;}public int ActiveMembers{get;set;}public int ActiveSubscriptions{get;set;}public List<ReportPlanRow> PlanBreakdown{get;set;}=new();public List<ReportBranchRow> BranchBreakdown{get;set;}=new();}public class ReportPlanRow{public string Name{get;set;}="";public int Subscriptions{get;set;}}public class ReportBranchRow{public string Name{get;set;}="";public int Members{get;set;}public decimal Revenue{get;set;}}
