<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Google.Apis.Admin.Directory.directory_v1" Version="1.76.0.4262" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.1">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\GymFit.Application\GymFit.Application.csproj" />
		<ProjectReference Include="..\GymFit.Domain\GymFit.Domain.csproj" />
	</ItemGroup>

</Project>
